language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
  - julia: nightly

script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/rafaqz/UnitfulConventionalMoles.jl"))'
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
