language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 0.6
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
  - julia: nightly

script:
  - julia --color=yes -e 'Pkg.clone("https://github.com/rafaqz/UnitfulMoles.jl.git"); Pkg.build("UnitfulMoles")'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("UnitfulConventionalMoles"); Pkg.test("UnitfulConventionalMoles"; coverage=true)'

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
