name = "UnitfulConventionalMoles"
uuid = "81c544f1-1180-4a30-9a27-d99e411e70a8"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[deps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulMoles = "999f2bd7-36bf-5ba7-9bc1-c9473aa75374"

[compat]
Unitful = "1"
UnitfulMoles = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
